config/routes.rb
Rails.application.routes.draw do
  root "posts#index"
  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]
  def index
    @posts = Post.order(id: :asc)
  end

  def new
    @post = Post.new
  end

  def create
    post = Post.create!(post_params)
    redirect_to post
  end

  def show
  end

  def edit
  end

  def update
    @post.update!(post_params)
    redirect_to @post
  end

  def destroy
    @post.destroy
    redirect_to @post
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end
  
  def post_params
    params.require(:post).permit(:title, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CarrierwaveApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to "投稿一覧", posts_path %> <%= link_to "新規投稿", new_post_path %>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: @post, local: true do |form| %>
  <p><%= form.text_field :title %></p>
  <p><%= form.file_field :image, accept: "image/png,image/jpeg,image/gif" %></p>
  <p><%= form.submit "送信" %></p>
<% end %>

app/views/posts/edit.html.erb
<h1>編集</h1>
<%= render "form" %>

app/views/posts/index.html.erb
<h1>投稿一覧</h1>
<table>
  <thead>
  <tr>
    <th scope="col">No.</th>
    <th scope="col">タイトル</th>
    <th scope="col"></th>
  </tr>
  </thead>
  <tbody>
  <% @posts.each.with_index(1) do |post, i| %>
    <tr>
      <th scope="row"><%= i %></th>
      <td><%= post.title %></td>
      <td>
        <%= link_to "詳細", post %>
        <%= link_to "編集", edit_post_path(post) %>
        <%= link_to "削除", post, method: :delete, data: { confirm: "削除しますか?" } %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/posts/new.html.erb
<h1>新規投稿</h1>
<%= render "form" %>

app/views/posts/show.html.erb
<h1>投稿詳細</h1>
<p><%= @post.title %></p>
<p><%= image_tag @post.image.thumb.url %></p>
<p><%= link_to "投稿一覧", posts_path %></p>